[error] java.util.concurrent.TimeoutException: Future timed out after [35000 milliseconds]
[error] 	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:212)
[error] 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:225)
[error] 	at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
[error] 	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
[error] 	at scala.concurrent.Await$.result(package.scala:124)
[error] 	at play.api.internal.libs.concurrent.CoordinatedShutdownSupport$.syncShutdown(CoordinatedShutdownSupport.scala:67)
[error] 	at play.core.server.AkkaHttpServer.stop(AkkaHttpServer.scala:449)
[error] 	at play.runsupport.Reloader$$anon$4.close(Reloader.scala:324)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:124)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:67)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error] 	at java.base/java.lang.Thread.run(Thread.java:832)
[error] (Compile / run) java.util.concurrent.TimeoutException: Future timed out after [35000 milliseconds]
